name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make -j$(nproc)
    - uses: actions/upload-artifact@v4
      with:
        name: Plugin
        path: 010005F00E036000
